name: mobile
description: E-tolls Mobile App
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.1
  qr_flutter: ^4.1.0

  cupertino_icons: ^1.0.2

  uuid: ^3.0.7
  flutter_phosphor_icons: ^0.0.1+6
  postgres: ^2.6.1

  http: ^0.13.6

  url_launcher: ^6.1.11
  provider: ^6.0.5
  cloud_firestore:

  firebase_core:
  firebase_auth: ^4.7.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/green-transaction-icon.png
    - assets/images/red-transaction-icon.png
    - assets/
    - assets/images/

  fonts:
    - family: HKGrotesk
      fonts:
        - asset: assets/fonts/HKGrotesk-Bold.otf
          weight: 700
        - asset: assets/fonts/HKGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/HKGrotesk-Regular.otf
          weight: 400
